name: flutter_analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: flutter_analyze_and_test
    runs-on: macos-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v4
      - name: set up flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'      # 例: 使用したいチャンネルを指定
          cache: true            # キャッシュを有効にして高速化を推奨
      - name: flutter doctor
        run: flutter doctor -v
      - name: flutter pub get
        run: flutter pub get
      - name: flutter analyze
        run: flutter analyze
      - name: flutter test
        run: flutter test
