name: flutter_analyze

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    strategy:
      matrix:
        os: [macos-12]
        flutter-version: ['3.24.1']
        flutter-channel: [stable]

    name: flutter_analyze
    runs-on: ${{ matrix.os }}
    steps:
      - name: set up repository
        uses: actions/checkout@v3
      - name: set up flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: ${{ matrix.flutter-channel }}
          cache: false
      - name: flutter doctor
        working-directory: .
        run: flutter doctor -v
      - name: flutter pub get
        working-directory: .
        run: flutter pub get
      - name: flutter analyze
        working-directory: .
        run: flutter analyze
      - name: flutter test
        working-directory: .
        run: flutter test
